# Generated by Django 2.2.4 on 2019-08-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demopartyuser',
            name='scene_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
