# Generated by Django 2.2.4 on 2019-08-20 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('demo_party_start', models.DateField()),
                ('demo_party_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemoPartyExternalURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DemoPartyLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address_extra', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=29, max_digits=32, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=29, max_digits=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoPartySeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Demo Party series',
            },
        ),
        migrations.CreateModel(
            name='DemoPartyVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Not going'), (1, 'Planning'), (2, 'Went')], default=1)),
                ('demo_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='parties.DemoParty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='demoparty',
            name='external_urls',
            field=models.ManyToManyField(related_name='demo_parties', to='parties.DemoPartyExternalURL'),
        ),
        migrations.AddField(
            model_name='demoparty',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demo_parties', to='parties.DemoPartyLocation'),
        ),
        migrations.AddField(
            model_name='demoparty',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='parties.DemoPartySeries'),
        ),
    ]
