# Generated by Django 2.2.4 on 2019-08-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoparty',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
