# Generated by Django 2.2.4 on 2019-08-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demopartyvisitor',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not going'), (1, 'Planning'), (2, 'Went')], default=1),
        ),
    ]
